#这里的配置 存在一个固有的规律
#可配置的项存在于 spring.factories 里的xxxProperties类 被xxxAutoConfiguration类装配
#xxxProperties又跟配置文件绑定

server:
  port: 80
spring:
  profiles:
    active: dev
#    active: test

---
server:
  port: 8080
spring:
  profiles: dev

---
server:
  port: 8081
spring:
  profiles: test
